name: cryptocurrency_flutter
description: A new Flutter project.

publish_to: 'none'

version: 3.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  nb_utils: ^6.0.7

  #Firebase
  firebase_core: ^2.23.0
  firebase_analytics: ^10.7.1
  firebase_crashlytics: ^3.4.5
  google_mobile_ads: ^3.1.0
  onesignal_flutter: ^5.0.4
  firebase_auth: ^4.14.1
  firebase_storage: ^11.5.2
  cloud_firestore: ^4.13.2

  # AppAnimations and functionality
  animated_bottom_navigation_bar: ^1.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  number_slide_animation: ^0.2.1

  #Charts
  chart_sparkline: ^1.0.14
  syncfusion_flutter_charts: ^23.2.4

  # Storage
  sqflite: ^2.3.0

  #API calling
  http: ^1.1.0
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.1
  flutter_linkify: ^6.0.0

  # System Info
  url_launcher: ^6.2.1
  share_plus: ^7.2.1

  # State Management Technique
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0

  # AUTHENTICATION
  google_sign_in: ^6.1.6
  the_apple_sign_in: ^1.1.1
  flutter_secure_storage: ^9.0.0

  image_picker: ^1.0.4


  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  # State Management Technique
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

#dependency_overrides:
  #  firebase_core_platform_interface: 4.5.1

  # flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:

  uses-material-design: true

  assets:
    - images/
    - lang/
    - assets/
    - images/chart_images/
    - images/app_images/
    - images/app_images/limit.json
    - images/social_images/
